# Generated by Django 6.0.2 on 2026-05-20 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_alter_documentdata_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_hash', models.CharField(help_text="The SHA-256 hash of the document content at the exact moment of signing. Ensures data hasn't changed.", max_length=64)),
                ('cryptographic_signature', models.TextField(help_text="The actual cryptographic signature string generated by the signer's private key.")),
                ('public_key', models.TextField(blank=True, help_text='The public key used to verify the signature (if you are utilizing asymmetric cryptography).')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user at the time of signing.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser or client information for audit purposes.')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
                ('signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document signature',
                'verbose_name_plural': 'document signatures',
                'ordering': ['-signed_at'],
            },
        ),
    ]
