# Generated by Django 6.0.2 on 2026-06-11 19:15

import signatures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignature',
            name='short_id',
            field=models.CharField(db_index=True, default=signatures.models.generate_short_id, editable=False, help_text='A unique 8-character hex ID for public verification.', max_length=8, unique=True),
        ),
    ]
