# Generated by Django 6.0.2 on 2026-06-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_documentsignature_short_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id_used', models.CharField(help_text='The ID the user attempted to look up.', max_length=20)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('tampered', 'Tampered'), ('not_found', 'Not Found'), ('error', 'Error')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='signatures.documentsignature')),
            ],
            options={
                'verbose_name': 'public verification log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
