import uuid

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from documents.models import Document


class DocumentSignature(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    document = models.ForeignKey(
        "documents.Document",
        on_delete=models.CASCADE,
        related_name="signatures"
    )
    signer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,  # Preserve the signature audit trail even if user is deleted
        null=True,
        related_name="signatures"
    )

    document_hash = models.CharField(
        max_length=64,
        help_text=_("The SHA-256 hash of the document content at the exact moment of signing. Ensures data hasn't changed.")
    )
    cryptographic_signature = models.TextField(
        help_text=_("The actual cryptographic signature string generated by the signer's private key.")
    )
    public_key = models.TextField(
        blank=True,
        help_text=_("The public key used to verify the signature (if you are utilizing asymmetric cryptography).")
    )

    ip_address = models.GenericIPAddressField(
        null=True,
        blank=True,
        help_text=_("IP address of the user at the time of signing.")
    )
    user_agent = models.TextField(
        blank=True,
        help_text=_("Browser or client information for audit purposes.")
    )
    signed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-signed_at"]
        verbose_name = "document signature"
        verbose_name_plural = "document signatures"

    def __str__(self):
        signer_name = self.signer.email if self.signer else "Unknown User"
        return f"Signature on {self.document.name} by {signer_name}"

    def clean(self):
        if self.pk is None:
            try:
                current_hash = self.document.data.content_hash
                if self.document_hash != current_hash:
                    raise ValidationError(_("The document hash does not match the current data. Data may have been modified."))
            except ObjectDoesNotExist:
                if self.document_hash != self.document.file_hash:
                    raise ValidationError(_("The file hash does not match."))

    def save(self, *args, **kwargs):
        is_new = self._state.adding

        self.clean()
        super().save(*args, **kwargs)

        if is_new and self.document.signing_status != Document.SigningStatus.SIGNED:
            self.document.signing_status = Document.SigningStatus.SIGNED
            self.document.save(update_fields=['signing_status'])

    def delete(self, *args, **kwargs):
        raise ValidationError(_("Signatures form a permanent audit trail and cannot be deleted."))
