# Generated by Django 6.0.2 on 2026-03-29 12:36

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(help_text='Size in bytes.')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (.xlsx)')], max_length=10)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('processing_error', models.TextField(blank=True)),
                ('signing_status', models.CharField(choices=[('unsigned', 'Unsigned'), ('signed', 'Signed'), ('changes_requested', 'Changes Requested')], db_index=True, default='unsigned', max_length=20)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('column_count', models.PositiveIntegerField(blank=True, null=True)),
                ('column_names', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='data', serialize=False, to='documents.document')),
                ('normalized_data', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document data',
                'verbose_name_plural': 'document data',
            },
        ),
    ]
