# Generated by Django 6.0.2 on 2026-05-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdata',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
