# Generated by Django 6.0.2 on 2026-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentdata_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (.xlsx)'), ('xls', 'Excel (.xls)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='signing_status',
            field=models.CharField(choices=[('unsigned', 'Unsigned'), ('signed', 'Signed')], db_index=True, default='unsigned', max_length=20),
        ),
    ]
