# Generated by Django 6.0.2 on 2026-06-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
